<?php

namespace Ctrlv\Lardmin\Tests;

use Ctrlv\Lardmin\Generators\BreadcrumbGenerator;
use Ctrlv\Lardmin\Generators\MenuGenerator;
use Ctrlv\Lardmin\Generators\UrlGenerator;

class BreadcrumbsGeneratorTest extends TestCase {

    private $breadcrumb_generator;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->breadcrumb_generator = $this->app->make(BreadcrumbGenerator::class);
    }

    public function testBreadcrumbsGeneratorLoaded()
    {
        $this->assertInstanceOf(BreadcrumbGenerator::class, $this->breadcrumb_generator);
    }

//    public function testBreadcrumbsGeneratorCanAdd()
//    {
//
//    }

}
